AMPATH/etl-rest-server

.gitignore
etl-dao.js

Reverts AMPATH/etl-rest-server#14

Revert e5c63e1d9d20c340320427e5a65432a998cf5360

---

etl-dao.js

age,
day(encounter_datetime) as day,
week(encounter_datetime) as week,
month(encounter_datetime) as month,
year(encounter_datetime) as year,
count(distinct if(arv_start_date is not null,person_id,null) as on_arvs

AA-337:Adding gender,

---

etl-factory.js
test/etl-factory.test.js
test/mock/mock-data.js

Refactored code to support testing

AA-497 Added report factory unit test

---

etl-routes.js
etl-server.js
package.json

Here is how config/config.js looks
```javascript
const tls = require('tls');
const fs = require('fs');
const settings = require('./settings.js');
const config = {};
const httpsServer = tls.createServer({
key: fs.readFileSync(settings.sslSettings.key),
cert: fs.readFileSync(settings.sslSettings.crt)
});
config.etl = {};
config.openmrs = {};
config.openmrs.host = 'test1.ampath.or.ke';
config.openmrs.port = 8443;
config.etl.host = 'localhost';
config.etl.tls = httpsServer;
config.etl.port = 8002;
module.exports = config;
```

ERS-4:Move etl properties that need to be configured into a configuration file

---

etl-routes.js
etl-server.js
package.json

Reverts AMPATH/etl-rest-server#81To combine all configuration in one file

Revert "ERS-4:Move etl properties that need to be configured into a configuration file"

---

etl-daemon.js
etl-factory.js
etl-server.js
reports/clinic-calander-report-v2.json
reports/indicators.json
reports/moh-731-report-v2.json
test/dao.test.js
test/mock/mock-data.js
uninstall-deamon.js

…d created report version 2 to generate the reports

AA-536-MOH731 Accurancy

---

dao/patient/etl-patient-dao.js
etl-helpers.js
reports/moh-731-cohort-allsites-report.json
reports/moh-731-indicator-allsites-report.json

… locations and include encounter type name in patient hiv summary report

AA-559:Updated etl all sites indicator and cohort to allow a subset of locations and include encounter type name in patient hiv summary report

---

dao/analytics/etl-analytics-dao.js
etl-factory.js
reports/clinical-reminder-report.json
reports/indicators.json

https://test1.ampath.or.ke:8443/test-builds/AA-572/#/url-selector

AA-572:Fix Clinical Reminder

---

reports/daily-visits-appointment.report.json

ERS-8:Update queries generating the patient list to match the numbers on the calender view

---

service/notes.service.js
test/service/notes.service.test.js

This facilitate sorting chronologically. I have also sorted assessments &
cc/hpi chronologically before sending the results to the client

ERS-63: Added obs datetime to cc/hpi & assessment

---

dao/eid/etl-eid-dao.js
etl-routes.js

Created a justifications endpoint.

ERS-110: Display viral load justification on posting form

---

reports/indicators.json

Reverts AMPATH/etl-rest-server#202

Revert "ERS-103:Update viral load pending reminder to account for lab errors in the Lab Data Summary."

---

authorization/etl-authorizer.js
dao/analytics/etl-analytics-dao.js
etl-factory.js
etl-routes.js
reports/clinic-lab-orders-report.json

ERS-127: Created Clinic lab orders report

---

etl-routes.js
package.json

Defined and created routes for:
-  daily-appointments,
- daily-visits
- daily-has-not-returned

NGPOC-163:Define and implement Daily Schedule routing and outputs

---

dao/clinic/etl-clinic-dao.js
etl-routes.js

Created the the defaulter list  route
Added getDefaulterList dao method to support multiple locations

ERS-142:Define and implement defaulter list routing

---

etl-routes.js

*Appointments
*Visits
*not returned

Added default groupBy to daily:

---

etl-routes.js

Added patientUuid request parameter
*Other code for definition of routing was incorporated into ERS-138

NGPOC-179:Define and implement patient reminders routing

---

reports/daily-visits-appointment.report.json

Added phone number
Excluded voided phone person attributes

NGPOC-268:Added phone number to list of missed appointments

---

etl-routes.js

Reverts AMPATH/etl-rest-server#398

Revert "NGPOC-365:Update patient list endpoint"

---

programs/program-visits-config.json

Added reason message to config

Added Condition Message to programs config

---

programs/program-visits-config.json

Added incompatibility property to program-visits-config.json on the program object.The incompatibility property consisits of program uuids that are incompatible with the program.To be used in program enrollment validation.

Added Incompatibilty property and data to Program visits-config.json

---

reports/indicators.json
service/patient-reminder.service.js

This PR Addresses bugs in viral load reminders.Change of logic was requested of how reminders are queried and classified.

NGPOC-377: Address and Implement Issues raised in APTS-86

---

programs/resolve-to-encounterId.js

Refactored resolve encounter uuid module to easily filter

APTS-558-559:Daily schedule/Monthly feedback fix

---

programs/program-visits-config.json

Reverts AMPATH/etl-rest-server#456

Revert "Included the correct uuid for transit form"

---

programs/program-visits-config.json

This PR adds Breast Cancer screening encounter which handled by ONCOLOGY POC Breast Cancer History and Risk Assessment Form v1.0

Added BreastCancer assessment encounter

---

dao/patient-referral/patient-referral-dao.js
etl-routes.js

ERS-216: Add updates to support updating patient referral notification

---

programs/patient-program-config.json

Inpatient Peer  POC Encounter Form v1.0 to all Standard HIV Visits

Add inpatient peer form

---

dao/patient/etl-patient-initial-encounters-dao.js
etl-routes.js
programs/patient-program-base.service.js
programs/patient-program-config.json
programs/program-visit-types.service.js
programs/scope-builder.service.js
test/programs/scope-builder.service.test.js

This PR allows PMTC to be able fill initial visit forms as they have been filling blue card return form without starting a visit.Once initial visit has been done it will go back to showing return visit

PMTC Initial visit

---

app/lab-integration/lab-sync-service.js
app/lab-integration/utils/eid-compare-operator.js

…f check on 0 being considered false

Fix issue with result comparison duplicating LDL results

---

app/reporting-framework/json-reports/combined-breast-cervical-cancer-monthly-screening-summary-base.json

POCONC 90: Change date format for amalgamated breast and cervical screening report

---

app/reporting-framework/json-reports/daily-has-not-returned-base.json

Reverts AMPATH/etl-rest-server#748

Revert "POCAMRS-245"

---

app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-base.json
etl-helpers.js
oncology-reports/oncology-reports-service.js
service/breast-cancer-monthly-summary.service.js
service/cervical-cancer-monthly-summary.service.js
service/combined-breast-cervical-cancer-monthly-summary.service.js
service/lung-cancer-monthly-summary.service.js
service/lung-cancer-treatment-summary.service.js

Presently, clients' names in oncology reports are not formatted to conform to any particular case. This PR formats those names to proper-case for consistency and ease of reading.

POCONC-167: Format client names in oncology patient lists to proper case

---

dao/patient/etl-patient-dao.js
etl-helpers.js
service/oncology/patient-oncology-summary-service.js

This PR revises the oncology screening and treatment program snapshots so that:
1. The screening snapshot contains the following information (if available) from the most recent breast or cervical cancer screening encounter:
- Screening done (breast or cervical cancer screening)
- Date
- Location
- Breast screening findings
- Cervical screening findings
2. The treatment snapshot contains the following information (if available) from the most recent program-specific encounter:
- Diagnosis
- Treatment plan
- Previous chemotherapy
- Current medication regimen
- Current chemo cycle
- Total chemo cycles planned
- Chemotherapy plan
- Chemotherapy intent
- Cancer stage group
- RTC date

POCONC-164: Revision of the screening and treatment program snapshots

---

programs/patient-data-resolver.service.js
programs/scope-builder.service.js

Reverts AMPATH/etl-rest-server#886

Revert "Modidied PEP Inital & Return visit validation to look at days since l…"

---

app/routes/surge-reports.route.js
service/surge-reports/surge-weeks.service.js

* Added endpoint to serve surge weeks for surge module
* code cleanup

Added endpoint to serve surge weeks for surge module (#1031)

---

README.md

Add new CI status badge

---

app/reporting-framework/json-reports/daily-attendance-base.json

HIV-823: Medication pickup RTC not showing on daily/monthly schedule visits

---

.github/workflows/deploy-beta.yml
.github/workflows/deploy-test-build.yml
.prettierignore

Build and publish docker image to `ampathke` docker hub

Integrate deployment pipeline workflow

---

.github/workflows/deploy-beta.yml

- Essential for spinning up ETL nomad job

ci: Extract branch name

---

service/oncology/patient-oncology-summary-service.js

Renames `prior_via_result_date` to `prior_via_date`.

Rename `prior_via_result_date` column

---

service/oncology/patient-oncology-summary-service.js

[Ticket](https://jira.ampath.or.ke/browse/POCONC-219)
Fixes to the patient summary snapshot generation logic.

POCONC-219: Fix patient summary snapshots

---

.github/workflows/deploy-beta.yml
.github/workflows/deploy-test-build.yml

Build, publish, & deploy ETL Test Builds

Deploy: Build, publish, & deploy etl-test-builds:(requires human approval)

---

app/family-history/family-history.service.js

HIV-705: Add contact age at elicitation column in family history dashboard

---

app/reporting-framework/json-reports/clinical-reminder-report.json
reports/clinical-reminder-report.json
service/patient-reminder.service.js

HIV-912: Update inh/ipt reminders with both 3 and 6 months tb prophylaxis drugs

---

app/reporting-framework/json-reports/clinical-reminder-report.json

- Factor in latest non clinical encounter with the VL results

Re-evalulate viral load (VL) reminders

---

reports/DQA/dqa-chart-abstraction-report-dao.js

- Add the ability to retrieve all patients

Add ability to retrieve all patients

---

reports/DQA/dqa-chart-abstraction-report-dao.js

Add TPT status

---

reports/DQA/dqa-chart-abstraction-report-dao.js

- Lag the last clinical encounter datetime

Fix: Pick the latest encounter datetime

---

programs/patient-program-config.json

- Show forms conditionally based on age & program enrolled in.

POC-51: Fix bug in DC standard visit and viremia visit

---

app/reporting-framework/json-reports/covid-19-summary-report-base.json
app/reporting-framework/json-reports/patient-list-with-contacts-template.json

- Fixes monthly screening numbers

POC-42: Fix covid report monthly screening numbers

---

app/reporting-framework/json-reports/prep-monthly-summary-base.json

This PR fixes disaggregation by population type numbers

POC-136: Fix disaggregation by population type numbers

---

docker/etl-rest-server/Dockerfile
docker/etl-rest-server/base/Dockerfile

- Introduce base image - re-use pre build node cache

Optimization: Faster docker builds

---

app/lab-integration/utils/lab-client.js

Increase the response timeout to allow successful fetching of results from EID

Fix ETL to EID timeout

---

etl-routes.js

Fix Boom.create() is not a function

Chores: Fix Boom.create() is not a function

---

programs/patient-program-config.json

- Removed required covid screening form for prep clients

POC-176: Remove required covid screening form for prep clients

---

app/reporting-framework/base-mysql.report.js
app/reporting-framework/json-reports/covid-19/covid-19-monthly-report.json
app/reporting-framework/json-reports/covid19-cumulative-summary-report-aggregate.json
app/reporting-framework/json-reports/covid19-cumulative-summary-report-base.json
app/reporting-framework/json-reports/hiv-monthly-not-screened-for-covid-base.json
app/reporting-framework/json-reports/hiv-monthly-on-art-15-and-above-report-aggregate.json
app/reporting-framework/json-reports/patient-list-covid-template.json

- Fixes discrepancies in covid 19 report indicators

POC-126: Fix descripancies in Covid 19 dashboard indicators

---

programs/patient-program-config.json

POC-311: Add MNCH Program Validations

---

programs/patient-program-config.json

POC-168: Add Mental health screening form to the Youth HIV Visits

---

app/reporting-framework/json-reports/clinical-reminder-report.json
service/patient-reminder.service.js

[POC 277 - Reminders not showing for the HIV clients not ever initiated on TPT](https://ampath.atlassian.net/browse/POC-277)

POC-277: Reminders not showing for the HIV clients not ever initiated on TPT

---

app/reporting-framework/hiv/moh-731.report.js
app/reporting-framework/json-reports/clinical-reminder-report.json
app/reporting-framework/json-reports/main-dataset-base-age15.json
app/reporting-framework/json-reports/main-dataset-base-age18.json
app/reporting-framework/json-reports/main-dataset-base-blue-card.json
app/reporting-framework/json-reports/main-dataset-base.json
app/reporting-framework/json-reports/ovc-in-hei-dataset-base.json
app/reporting-framework/json-reports/ovc-in-hiv-dataset-base.json
app/reporting-framework/json-reports/patient-list-frozen-template.json
app/reporting-framework/json-reports/patient-list-template.json
app/reporting-framework/json-reports/patient-list-with-contacts-template.json
app/reporting-framework/json-reports/regimen-dataset-base.json
app/reporting-framework/json-reports/retention-dataset-base.json
app/reporting-framework/json-reports/starting-art-base-age-green.json
app/reporting-framework/json-reports/starting-art-base-age15.json
app/reporting-framework/json-reports/tb-preventive-dataset-base.json

Fix the MOH report patient list to show the most recent vl results from the flat_lab_and_imaging table rather than from HIV summary.

Fix vl issue

---

service/patient-reminder.service.js

- clean terminal console by removing unnecessary console logs

(fix):  Remove superflous console logs

---

app/reporting-framework/base-mysql.report.js
app/reporting-framework/json-reports/ml-predictions/ml-weekly-predictions-aggregate.json
app/reporting-framework/json-reports/ml-predictions/ml-weekly-predictions-base.json
app/routes/ml-weekly-predictions.route.js
etl-routes.js
programs/patient-program-config.json
service/ml-weekly-predictions.service.js
service/predictions/ml-prediction-service.js

- Adds ML weekly predictions endpoint

ML weekly predictions API endpoint for patient list

---

service/eid/eid-facility-mappings.json

KESSES was mapped as a burnt forest satellite location.

re-map kesses to right mfl

---

dao/patient/etl-patient-dao.js

Added the part that retrieves data from flat_hei_summary, flat_vitals, and flat_obs.

POC-397: HEI summaries configurations

---

reports/DQA/dqa-chart-abstraction-report-dao.js

POC-610: Optimized the DQA Query

---

reports/DQA/dqa-chart-abstraction-report-dao.js

POC-610: Modified query to get DQA as per nascop indicators
POC-610: Updated DQA Report to reflect updated indicators

POC-610: Modified DQA Query to suit indicators requested

---

service/cervical-cancer-screening-service.js

Missing cancer screening results in patient snapshot and HIV summary

POC-666: ETL- Missing cancer screening results in patient snapshot and HIV summary

---

app/amrs-3.x/amrs_id.js
etl-routes.js
package-lock.json

(feat) added amrs id for AMRS 3.X

---

service/cervical-cancer-screening-service.js

Backend: etl-rest-server to test feature POC-667 CaCx - Clients indicated to have been done Total Abdominal hysterectomy and yet no documentation in the system

POC-667: Clients indicated to have been done Total Abdominal hysterectomy and yet no documentation in the system

---

app/lab-integration/utils/lab-client.js
app/lab-integration/utils/poc-eid-payload-helper.js

POC-781: added HPV payload to etl

---

app/reporting-framework/hiv/moh-731.report.js
app/reporting-framework/json-reports/clinical-reminder-report.json
app/reporting-framework/json-reports/patient-list-template.json
app/reporting-framework/json-reports/patient-list-with-contacts-template.json
app/reporting-framework/json-reports/surge-report-base.json
app/reporting-framework/json-reports/tb-preventive-dataset-base.json
dao/patient/etl-patient-dao.js

Reverts AMPATH/etl-rest-server#1404

Revert "ensured only max vl_date is picked"

---

dao/patient/etl-patient-dao.js

POC-907: Fixed the error on hpv query

---

programs/patient-data-resolver.service.js
programs/patient-program-config.json
programs/scope-builder.service.js
service/openmrs-rest/obs.service.js

Add Turbo MCH to Prediction Facilities List

Poc 1083 a

---

programs/patient-program-config.json

Created PrEP Study Delivery Visit and removed prep study return visit

POC-1088: Created PrEP Study Delivery Visit and removed prep study return visit

---

programs/scope-builder.service.js

Fixed PrEP program config to allow for previous clients without PrEP status concept

POC-1088C: Fixed PrEP program config to allow for previous clients without PrEP status concept

---

programs/patient-program-config.json

Rearrange the DSD visits so that it appears at the top

POC-1064: Rearrange the DSD visits so that it appears at the top
