reports/hiv-summary-monthly-report.json, reports/indicators.json
This PR contains the definition for TX_TB indicators, TB_PREV and TB_INH indicators. The former two are required for DATIM-USAID reporting by the TB department.
=> APTS-170: Included TB Indicators

encounter-type/encounter-type-service.js, programs/program-type.service.js, resolve-program-visit-encounter-Ids/resolve-program-visit-encounter-Ids.js, visit-type/visit-type-service.js
This PR fixes the issue where an encounter type is defined in configs but it is not found in the encounter type table
=> Fixed issue where encounter type is in configs but not in table

programs/patient-data-resolver.service.js, programs/patient-program-base.service.js, programs/patient-program-config.json, programs/scope-builder.service.js
This ticket adds two new visit types as well as visit-level validation to the Pre-Exposure Prophylaxis (PrEP) program. 
Previously, upon starting a PrEP visit, the system would display both Initial and Return encounter forms for clients enrolled in the PrEP program regardless of whether they had previous PrEP encounters or not. 
This ticket fixes this problem by replacing the original PrEP visit with two new visit types: PrEP Initial visit and PrEP Return visit. It also validates the new visits so that:
- If a patient had a PrEP encounter, the Return visit is displayed while the Initial visit is hidden.
- Otherwise, if a patient did not have a PrEP encounter, the Initial visit is displayed while the Return visit is hidden.
=> POCAMRS-269: Add Validation to PrEP visit

programs/patient-program-base.service.js, programs/patient-program-config.json, programs/program-visit-types.service.js, programs/scope-builder.service.js
This ticket modifies oncology treatment programs in the following ways:
1. Addition of an Initial visit and a Return visit into each program.
2. Addition of a Pharmacy visit and a Lab visit shared across all of the programs.
3. Addition of visit-level validation to Initial and Return visits so that:
- If a patient has had a previous encounter, the Initial visit is displayed while the Return visit is hidden.
- If a patient has not had an encounter, the Return visit is displayed while the Initial visit is hidden.
The programs it affects are:
- Lung cancer treatment
- General oncology
- Breast cancer treatment
- Sickle cell treatment
- Hemophilia treatment
- Multiple myeloma
- Lymphoma treatment * (Initial and Return encounter types yet to be created by the Lymphoma team)
=> POCONC-147: Visit types changes for oncology treatment programs

programs/patient-program-config.json, programs/scope-builder.service.js
This ticket adds visit-level validation to the Anticoagulation Treatment Program. It replaces the original Anticoagulation Treatment visit with four new visit types:
- Anticoagulation Initial visit
- Anticoagulation Return visit
- Pharmacy visit
- Lab visit
It introduces validation to the Initial and Return visits so that:
- If a patient has not had an encounter, the Initial visit is displayed while the Return visit is hidden.
- If a patient has had a previous encounter, the Return visit is displayed while the Initial visit is hidden.
It also changes the validation logic previously applied to the other Oncology treatment programs so that it now validates against the program in addition to the encounter type.
=> POCONC-151: Validate visit types for Anticoagulation program

programs/patient-program-config.json, programs/scope-builder.service.js
Previously, upon starting a PEP visit, the system would display both Initial and Return encounter forms for clients enrolled in the PEP program regardless of whether they had previous PEP encounters or not.
This ticket replaces the PEP visit with two new visit types: PEP Initial and PEP Return. It also adds validation to the new visit types so that:
- If a patient did not have a PEP encounter, the Initial visit is displayed while the Return visit is hidden.
- Otherwise, If a patient had a PEP encounter, the Return visit is displayed while the Initial visit is hidden.
=> POCAMRS-273: Add validation to PEP visit

programs/patient-program-config.json
Adds Youth Return Form to the Standard HIV Visit for Differentiated Care in the Differentiated Care Program.
=> HIV-427: Add Youth Return encounter type to Standard HIV Visit in the DC Program

service/eid/eid-facility-mappings.json
The master facility list (MFL) code we have on record for the Moi University clinic is not the same as what appears on the Kenya Master Health Facility List website http://kmhfl.health.go.ke/#/home and the EID lab system. This commit changes the MFL code for that facility to the correct one.
=> EID-FIX: Fix incorrect mflCode for Moi University Main Campus clinic

programs/patient-program-config.json
The changes introduced add visit level validation to the cervical cancer screening visit so that only female clients are considered eligible.
=> POCONC-158: Fix male patients being eligible for cervical screening visit

etl-helpers.js
This commit fixes the following issues with the oncology snapshot summary (#779) :
- 'Invalid date' being displayed on the snapshot for NULL dates.
=> POCONC-159: Fixes and improvements to the oncology snapshot display

app/routes/patient-medication-history.route.js
Presently, the date being displayed on the medication history summary in the oncology screening and diagnosis program summary is in ISO 8601 format e.g. 2019-01-23T10:20:06.000Z. The fix introduced changes it to the more readable YYYY-MM-DD format e.g 2019-01-23.
=> POCONC-160: Fix medication history date on oncology diagnosis summary

app/reporting-framework/json-reports/referral-dataset-base.json
This commit fixes the referral patient list feature for Hemato-Oncology and CDM programs following a breaking change from [#1067](https://github.com/AMPATH/ng2-amrs/pull/1067). It also introduces a referred_to column that indicates the location to which the patient is being referred.
=> POCONC-165: Referral Patient list fixes and improvements

app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-base.json
Change the name of the referred_orderd column in the breast_cancer_screening report to referrals_ordered. This change is necessitated by the column name being changed in the database table.
=> POCONC-171: Rename referred_orderd column to referrals_ordered

app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-base.json, app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-base.json
A bug with the logic used to disaggregate breast and cervical screening findings by age is causing patients aged exactly 70 years old not to appear on the aggregate report counts as well as the patient lists. The check currently being used to determine whether a patient is in the over 70 years age segment only checks for whether the patient's age is above 70 years old. Patients aged 70 are being bypassed by that check.
=> POCONC-174: Patients aged 70 yrs old not appearing in patient lists

app/reporting-framework/json-reports/breast-cancer-daily-screening-summary-aggregate.json, app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-aggregate.json, app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-base.json, app/reporting-framework/json-reports/cervical-cancer-daily-screening-summary-aggregate.json, app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-aggregate.json, app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-base.json, oncology-reports/oncology-patient-list-cols.json
This PR adds new columns to the breast screening and cervical screening reports. The following columns are added to the breast screening and cervical screening aggregate report:
- male_patients (count) (breast only)
- female_patients (count) (breast only)
- hiv_negative (count)
- hiv_status_unknown (count)
- hiv_positive (count)
The columns in the aggregate are also reordered so that normal and abnormal findings are arranged consecutively for easier side-by-side comparison. The Location and Period columns are pinned so that they always stay visible when scrolling across the report. 
It also modifies the patient list for breast screening patients with abnormal findings to include the following columns:
- breast_mass_location
- nipple_discharge_location
- nipple_retraction_location
- …
=> POCONC-172: Add columns to breast & cervical patient lists for abnormal findings

app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-base.json
Add extra concept mappings for the following columns to the cervical cancer screening base report:
- `visual_impression_cervix`
- `visual_impression_vagina`
- `visual_impression_vulva`
- `via_procedure_done`
- `via_management_plan` 
This is necessitated by the addition of the new mappings to the cervical cancer screening stored procedure.
=> POCONC-176: Minor modifications to cervical cancer screening base columns

app/reporting-framework/json-reports/breast-cancer-daily-screening-summary-aggregate.json, app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-aggregate.json, app/reporting-framework/json-reports/breast-cancer-monthly-screening-summary-base.json, app/reporting-framework/json-reports/breast-cancer-patient-list-template.json, app/reporting-framework/json-reports/cervical-cancer-daily-screening-summary-aggregate.json, app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-aggregate.json, app/reporting-framework/json-reports/cervical-cancer-monthly-screening-summary-base.json, oncology-reports/oncology-patient-list-cols.json
Add HIV status disaggregation by age to the oncology reports so that data about clients' HIV status in various age segments can be derived. These age segments are:
- Under 25 years
- 25 - 49 years
- Over 50 years
The HIV statuses that ought to be shown are:
- HIV Positive
- HIV Negative
- HIV Status Unknown
=> POCONC-173: Add HIV status disaggregation by age to oncology reports

app/routes/oncology-integrated-program-snapshot.route.js, service/oncology/patient-oncology-summary-service.js
Add HIV status, encounter type and data about cervical cancer screening findings from previous encounters (if present) to the summary snapshots of patients enrolled in the Oncology screening and diagnosis program.
=> POCONC-178: Add hiv_status, prior_via_test and prior_via_test_result to summary snapshots

app/reporting-framework/json-reports/lung-cancer-treatment-monthly-summary-base.json, oncology-reports/oncology-patient-list-cols.json
Add the following columns to the lung cancer treatment program patient lists:
`sticks_smoked_per_day`
`education_level`
`marital_status`
`age_at_diagnosis`
`chemo_start_date`
`chemo_stop_date`
`overall_cancer_staging`
`lung_cancer_type`
`non_small_cell_lung_cancer_type`
=> POCONC-179: Add columns to lung cancer treatment patient lists

app/reporting-framework/json-reports/lung-cancer-daily-screening-summary-aggregate.json, app/reporting-framework/json-reports/lung-cancer-monthly-screening-summary-aggregate.json, app/reporting-framework/json-reports/lung-cancer-monthly-screening-summary-base.json, oncology-reports/oncology-patient-list-cols.json
Minor modifications to column names in the lung cancer screening report following amendments to the stored procedure. These include:
- Rename `tb_treatment_received` to `previously_treated_for_tb`.
- Rename `no_tb_treatment` to `not_previously_treated_for_tb`.
- Rename `indication_of_mediastial_mass_from_ct_findings` to `indication_of_mediastinal_mass_from_ct_findings`.
- Rename `non_respiratory_disease` to `non_cancer_respiratory_disease`.
- Rename `tobacco_use` to `uses_tobacco`.
- Rename `ever_smoked_cigarettes` to `smokes_cigarettes`.
- Change case options for the `referrals` and `type_of_non_cancer_respiratory_diseases` columns so that they reference the associated concept ids.
- Change case for the results of case options for `referrals` and `type_of_non_cancer_respiratory_diseases` …
=> POCONC-191: Further amendments to lung cancer screening report

app/reporting-framework/base-mysql.report.js, app/reporting-framework/json-reports/referral-dataset-base.json, app/reporting-framework/json-reports/referral-peer-base.json, etl-routes.js, service/patient-referral.service.js
Presently, referral patient lists (_found under Clinic Dashboard > Patient Referral_) for the Hemato-Oncology and CDM departments are not working as they should.
The logic for this feature was written such that both departments could reuse the same base and aggregate reports, as well as displaying the same report indicators in the UI. The shared URL endpoint for these reports was modified at some point, which is why they stopped working. The aim of this change was likely to try and get the peer navigator tracking patient list used by the CDM department working. Currently, neither the peer navigator tracking patient list nor the referral patient lists are working in production.
This PR sets the URL endpoint back to the appropriate one and gets the referral patient lists back working again. …
=> POCONC-192: Fix shared referral patient lists

programs/scope-builder.service.js
This PR increases the validation period for PEP initial visits from 28 to 60 days i.e. clients should be eligible for a PEP initial visit if they return to clinic 60 days or later since their first PEP initial.
=> Increase PEP visit validation duration period to 60 days

README.md
This PR modifies the Travis status badge URLs to point to the new [domain](https:travis-ci.com) following the migration of this repo's CI.
=> Point travis status badge to new URL

.travis.yml
This PR adds a lint step to Travis that checks that all code pushed to the repo matches the formatting style defined in our barebones (default) config. Now that all files are formatted, it would be wise to keep the repo pristine.
=> Add lint step to CI

package.json
Add `json` file format to the glob patterns considered by lint-staged for automatic formatting pre-commit. Solves the problem of json files with lint errors breaking CI builds.
=> Add json to lint-staged glob patterns

.babelrc, package-lock.json, package.json
Upgrade the Babel version from v6.x.x to [v7](https://babeljs.io/docs/en/v7-migration).
Babel v6 was released in 2015. Since then it has gone through over 5000 commits and hundreds of releases. Babel 7 is faster and comes with an upgrade tool (used here), JavaScript configurations, configuration overrides, options for size minifications and TypeScript support amongst a whole host of improvements. Upgrading to Babel 7 sets the stage for us to transition over to modern JavaScript tooling for industry best practices such as linting via ESLint and testing using the Jest framework.
=> chore: Upgrade to Babel v7

service/patient-reminder.service.js
Some grammatical amendments to the reminders copy that I thought would be useful. I noticed these while working on the `PatientReminder` service test suite.
=> Grammatical fixes to reminders copy

package.json
It's pretty annoying to have your PR fail a CI status check because Prettier didn't run on your staged files pre-commit. This PR fixes that by explicitly calling `prettier --check` in the pre-commit hook.
=> Run prettier check pre-commit

app/family-history/family-history.service.js, app/reporting-framework/json-reports/daily-has-not-returned-base.json, app/reporting-framework/json-reports/hiv-summary-base.json, app/reporting-framework/json-reports/main-dataset-base-blue-card.json, app/reporting-framework/json-reports/main-dataset-base.json, app/reporting-framework/json-reports/ovc-in-hei-patient-list-template.json, app/reporting-framework/json-reports/patient-gains-and-losses-patient-list-template.json, app/reporting-framework/json-reports/patient-list-schedules-template.json, app/reporting-framework/json-reports/starting-art-base-age15.json
Add a fix to remove limit for the clients reviewed filter and fix bugs in queries
=> Poc 115b patch

app/reporting-framework/json-reports/patient-list-schedules-template.json, app/reporting-framework/json-reports/patient-list-template.json, app/reporting-framework/json-reports/patient-list-with-contacts-template.json
Add columns to daily schedule patient list to show sms delivery status for patients who consented to receive sms
=> Add columns to daily schedule to show sms delivery status

app/reporting-framework/json-reports/clinical-reminder-report.json, service/patient-reminder.service.js
- Adds  warning reminder & alert for appointment no show risk
=> POC-438: Add alert/reminder to indicate patient risk score

service/cervical-cancer-screening-service.js, service/patient-reminder.service.js
POC-607: Remove cancer screening reminder for clients done hysterectomy
=> POC-607: Remove cancer screening reminder for clients done hysterectomy
